# Generated by Django 3.2.3 on 2021-06-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mo_no',
            field=models.IntegerField(),
        ),
    ]
