# Generated by Django 3.2.3 on 2021-06-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_person_mo_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hd_orphan',
            field=models.BooleanField(default=False),
        ),
    ]
