# Generated by Django 3.2.3 on 2021-06-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_person_hd_orphan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='firstapp.person')),
                ('School', models.CharField(max_length=50)),
                ('College', models.CharField(max_length=50)),
                ('Aggregate', models.FloatField(max_length=5)),
            ],
            bases=('firstapp.person',),
        ),
    ]
