# Generated by Django 3.2.3 on 2021-06-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mo_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
